### ISSUE TITLE
Getting erros at blank fields

### ISSUE THREAD

**Issue by yasinmoha** [dnel/BusinessHours#3]
Hi...

I am using this functions for getting the business hours and days. I am running this through a pandas dataframe while using the business days function if the time span is less than a day. I am getting -1 instead of 0

and while using gethours if the field is blank I am getting the error below I ran it both in Python 2.7 and 3.5 

OverflowError: Python int too large to convert to C long.

Below is how I am calling the code. 

list1 = []
for index , start , end in df[['sys_created_on' , 'resolved_at' ]].itertuples():
    bh = BusHours(start , end  , worktiming=[7 , 17] , weekends=[6,7])
    a = bh.getdays()
    list1.append(a)
    
list2 = []
for index , start , end in df[['sys_created_on' , 'resolved_at' ]].itertuples():
    bh = BusHours(start , end  , worktiming=[7 , 17] , weekends=[6,7])
    b = bh.gethours()
    list2.append(b)

**Comment by dnel** [comment]
Hi, do you have any example input data where you are seeing the miscalculation with the days function occur?

WRT the second issue, there is no error handling for invalid/missing input data, for my own use I put this into the scripts calling this module. It doesn't fail gracefully, that could be improved but it wouldn't change the end result.

**Comment by yasinmoha** [comment]
[final.xlsx](https://github.com/dnel/BusinessHours/files/1526334/final.xlsx)

Attaching the sample file

**Comment by dnel** [comment]
I have fixed the logic error of getdays() and it is now returning better results. I have updated the README to clarify how these results should be interpreted.
