### ISSUE TITLE
Python end datetime calculate based on start datetime, duration and Business working hours

### ISSUE THREAD

**Issue by prakashjain** [dnel/BusinessHours#4]
Not Issue 
I would like to calculate End Date time based on below Input 
Start Date Time 
Duration 
Working Hours, Holidays and Weekend days are configurable.
Example:
    def __init__(self,  startdatetime, duration, worktiming=[9, 17],
weekends=[6, 7]):
Based on above parameters need to get enddatetime.

**Comment by dnel** [comment]
You will need to add the duration to the start datetime to create an end datetime and pass them for calculation as normal. This isn't something the module will do by itself.

**Comment by prakashjain** [comment]
""" Hello Dnel,
   Tried below code to calculate End Date Based on Start Date and Duration
   Exclude weekend and Holidays
   But the below code facing issue
if monday is on the starting date.. then script is working
if start date any other date not get exact output. 
Can you please help me to fix the error? Thanks in advance
"""
import datetime

# you can chnage duration from here
start_datetime = "07/07/2018 09:00:00"
# You can change the duarion from here
duration = 8
holidays = ['18/1/2018', '27/1/2018', '3/2/2018', '8/8/2018']

start = datetime.datetime.strptime(start_datetime, "%d/%m/%Y %H:%M:%S")
# working hours between 10:00AM and 6:00PM are 8 so
working_hour_per_day = 8
# excluding sunday
total_working_hour_per_week = 8 * 6

duration_in_weeks = duration // total_working_hour_per_week

duration_in_days = (duration - duration_in_weeks * 8 * 6) // working_hour_per_day

left_duration_in_hours = duration - duration_in_weeks * 8 * 6 - duration_in_days * 8

# now let's create a timedelta object

delta = datetime.timedelta(days=7 * duration_in_weeks + duration_in_days, hours=left_duration_in_hours, minutes=0)
temporary_end_date = start + delta

# new added code to find the holidays in the given duartion and modifying the end date
a = 0
for i in holidays:
    i = datetime.datetime.strptime(i, "%d/%m/%Y")
    if start <= i <= temporary_end_date:
        a += 1
        temporary_end_date += datetime.timedelta(days=1)
end_date = temporary_end_date

print(end_date.strftime("%d/%m/%Y %H:%M:%S"))
